### ISSUE TITLE
Are ProjectRef's to other, external SBT projects supported?

### ISSUE THREAD

**Issue by benhutchison** [dwijnand/sbt-project-graph#26] opened 2018-01-06 12:12 UTC
I have a SBT project containing a scala.js Cross Project.

Both the JS and JVM sub-projects depend upon the JS/JVM parts of another (external) cross-project at a relative file path. They do this by creating `ProjectRef`s, eg `ProjectRef(file("../time", "TimeJVM")`.

What I observed when I generated & viewed the dot file was that these dependencies were missing.

**Comment by dwijnand** [comment] 2018-01-08 11:03
Yeah when I wrote sbt-project-graph I didn't understand how sbt does multiple builds. See how I only use the current build:

https://github.com/dwijnand/sbt-project-graph/blob/v0.2.2/src/main/scala/sbtprojectgraph/SbtProjectGraphPlugin.scala#L18

This would be a great contribution.

**Comment by dwijnand** [comment] 2018-05-25 11:36
Duplicate of #8

**Closed by dwijnand** 2018-05-25 11:36 UTC
Labels: good first issue, help wanted
